version: "3.7"
services:
  crawler-db:
    image: postgres:latest
    volumes:
      - crawler_pg:/docker-entrypoint-initdb.d/
    ports:
      - "5445:5432"
    environment:
      - POSTGRES_DB=crawler
      - POSTGRES_USER=crawler
      - POSTGRES_PASSWORD=crawler

  crawler-scala:
    image: sbtscala/scala-sbt:eclipse-temurin-alpine-17.0.10_7_1.10.2_3.5.1
    volumes:
      - .:/app:cached
      - sbt_cache:/root
    ports:
      - "3030:3030"
    environment:
        # APP
      - APP_VERSION=0.0.1-SNAPSHOT # need to specify the version for the application and cache

        # Client (sttp):
      - CLIENT_TIMEOUT_PER_REQUEST=10 seconds # timeout to get result by url

        # Crawl:
      - CRAWL_MAX_POOL_REQUESTS=10 # maximum number of requests to send by url in parallel

        # Database:
      - POSTGRES_HOST=crawler-db  # db host
      - POSTGRES_PORT=5432        # db port
      - POSTGRES_DB=crawler       # database name
      - POSTGRES_USERNAME=crawler # credentials
      - POSTGRES_PASSWORD=crawler # credentials
      - POSTGRES_MAX_POOL_SIZE=10 # max pool of connections to postgresql

        # Security
      - ACCESS_TOKEN=khJAFbyV3pG5Ed8nBaUTYMIeCX9rqLsvWPZ247uS # token to access to crawl endpoint

        # Server
      - SERVER_HOST=0.0.0.0     # host of application server
      - SERVER_PORT=3030        # port of application server
      - SWAGGER_ENABLED=true    # enable swagger endpoint
      - SWAGGER_TITLE=API       # title of swagger web service
      - SWAGGER_ENDPOINT=admin  # endpoint of swagger service
      - SWAGGER_API_VERSION=1.0 # version of api (UI)

        # Cache:
      - CACHE_ENABLED=true                 # to enable caching
      - CACHE_SUCCESS_URL_TTL=10 minutes   # cache - time to live urls with success response
      - CACHE_FAILURE_URL_TTL=5 minute     # cache - time to live urls with failure response
      - CACHE_CLEANER_AWAKE_EVERY=1 minute # cache - cleaner delete old raws from cache (ttl < NOW())
    command: bash -c "cd /app && sbt run"

volumes:
  sbt_cache:
  crawler_pg: